version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run:
          name: Install All Dependencies
          command: npm install

      - run:
          name: Run eslint
          command: npm run lint

      - run:
          name: Run Test
          command: npm test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
